### ISSUE TITLE
曲線スライド

### ISSUE THREAD

**Issue by EbiseLutica** [paralleltree/Ched#11]
ほしいですね...

**Comment by paralleltree** [comment]
率直なところエクスポート先での描画の詳細が分からない、というか分かるほどコード追いかける体力がないのと、単純に描画がしんどくなりそうなので実装する予定はないです……。ゆるしてください……。

**Comment by EbiseLutica** [comment]
そうですか(´・ω・`)

うまく行きそうな方法が思いついたらこちらも手を貸します。
