### ISSUE TITLE
Tickの約数に対応できない音符がズレていく

### ISSUE THREAD

**Issue by paralleltree** [paralleltree/Ched#15]
切り捨てられた誤差Tickがどんどん累積して見るも無残な姿に

![image](https://user-images.githubusercontent.com/7324519/42880877-d4b1050c-8ad0-11e8-8588-fbc5f60689b4.png)
(14分音符を100小節目に配置しようとした例)

小節頭からクォンタイズさせるかTicksPerBeatいじれるようにしてカスタム音符指定時に端数が出たら警告したりしなかったりする(しろ)

**Comment by paralleltree** [comment]
とりあえずクォンタイズ単位をdoubleにしてごり押し

**Comment by paralleltree** [comment]
とりあえずクローズということにしておく

**Comment by JapanYoshi** [comment]
カスタムクオンタイズをするときは、一拍の長さを四捨五入して掛け算するのではなく、一小節の長さを割り算して結果を四捨五入するのが正解です。

計算例：
ticks per beat 192 で 10分音符を計算する場合

誤：
192 // 10 * 1 = 19
192 // 10 * 2 = 38
192 // 10 * 3 = 57
...
192 // 10 * 9 = 171
192 // 10 * 10 = 190 ← これが192のはず

正：
192 * 1 // 10 = 19
192 * 2 // 10 = 38
192 * 3 // 10 = 58 ← 57.6を繰り上げ
...
192 * 9 // 10 = 173
192 * 10 // 10 = 192

**Comment by paralleltree** [comment]
次の小節の頭に配置されるときはぴったりになる実装だったんですが途中は雑に切り捨ててたのであまりよろしくなかったですね……
