### ISSUE TITLE
斜めAIRの反転時にAIRの左右も反転させる

### ISSUE THREAD

**Issue by EbiseLutica** [paralleltree/Ched#17]
斜めAIRを使った地帯を反転したときに、斜めAIRも反転してほしいなあと思うときが頻繁にあるので、オンオフ切替可能な機能として追加してほしいです

もし多忙でしたら協力します。ご検討お願いします

**Comment by paralleltree** [comment]
すっかり忘れてました……

**Comment by EbiseLutica** [comment]
バグだったんですね

**Comment by paralleltree** [comment]
実質バグですねこれは

**Comment by paralleltree** [comment]
1bf5d4d7c で閉じた(コミットメッセージをミスるな)
