### ISSUE TITLE
ノーツの種類（など）をショートカットキーで選択

### ISSUE THREAD

**Issue by JapanYoshi** [paralleltree/Ched#36]
もちろん設定で変更できるもので。

・ノーツの種類
・ツール（ノーツの種類をホットキーで選択したら自動的に編集モードにする、他2つのツールはホットキーで）
・クオンタイズ変更（前、次）

**Comment by paralleltree** [comment]
とりあえず[v3.1.0](https://github.com/paralleltree/Ched/releases/tag/v3.1.0.0)で実装
