### ISSUE TITLE
HOLD・SLIDEを複数つなぐ、分割する

### ISSUE THREAD

**Issue by JapanYoshi** [paralleltree/Ched#38]
https://github.com/paralleltree/Ched/issues/37 を見て思いついた機能

![image](https://user-images.githubusercontent.com/8707990/59646568-dbdab980-91ba-11e9-967c-39439911fad4.png)
要するに、この二つを変換する機能

**Comment by paralleltree** [comment]
[スライド分割プラグイン](https://github.com/paralleltree/Ched/blob/d0c74620577835d474e5e3fd1a23d6471738c7e7/Ched/Plugins/SlideSplitter.cs)/[スライド結合プラグイン](https://github.com/paralleltree/Ched/blob/d0c74620577835d474e5e3fd1a23d6471738c7e7/Ched/Plugins/SlideMerger.cs)とは別物ですか？

**Comment by JapanYoshi** [comment]
なるほど、プラグインでしたか。

そういえば、「スライド編み込み」って何ですか？

**Comment by paralleltree** [comment]
神威[MAS]に配置されているようなスライドを作成するプラグインです。
詳細については[Wiki](https://github.com/paralleltree/Ched/wiki/BuiltInPlugins)を参照願います。
