### ISSUE TITLE
slide curve question

### ISSUE THREAD

**Issue by Seeker98** [paralleltree/Ched#42]
![image](https://user-images.githubusercontent.com/26476171/81549130-da0c7c80-93b0-11ea-80ee-b5cfef811752.png)
how to add curve slide like this or not supported now?

**Comment by JapanYoshi** [comment]
Chunithm doesn't use Bézier curves for holds and uses invisible slide waypoints to simulate a finer curve. You can take the same approach on Ched too.

**Comment by paralleltree** [comment]
Thank you for your reply, @JapanYoshi.
Ched does not support smoothed curve slide and I don't plan to implement it because of its complexity and maintainability.
