### ISSUE TITLE
重複ショートノーツのエクスポートができない

### ISSUE THREAD

**Issue by zZjurijuriZz** [paralleltree/Ched#5]
ノーツ同士が重なるとエクスポートエラーがでます。
特に、AIR-Actionの下にAIRを配置するとエラーがでるという致命的なミスがあります。
あとついでに要望なのですがAIRのサイズも変えられるようにしてほしいです^^

**Comment by paralleltree** [comment]
AIR-ACTIONの下にAIRを配置した際のエラーが再現できないので譜面の画像を貼ってもらえませんか？

**Comment by zZjurijuriZz** [comment]
了解です。
現在外出中なので午後6時くらいに送りますね。


2018/02/24 午前10:35 "Paralleltree" <notifications@github.com>:

AIR-ACTIONの下にAIRを配置した際のエラーが再現できないので譜面の画像を貼ってもらえませんか？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/paralleltree/Ched/issues/5#issuecomment-368185827>, or mute
the thread

**Comment by zZjurijuriZz** [comment]
間違いでした。申し訳ないです。こちら側のミスだったようです...

**Comment by paralleltree** [comment]
了解しました。ミスとのことですが、エラーが発生し得る状態であるのは不適切ですので内容を把握したいと考えています。
もしエラーが発生していた場合は実行フォルダに出力される`exception.json`をお送りください。

**Comment by zZjurijuriZz** [comment]
https://www.dropbox.com/s/jquzn3zkgj4yqox/exception.json?dl=0
こちらです。

**Comment by paralleltree** [comment]
確認しました。修正次第クローズします。
